server_name: "cora.local"
pid_file: /data/homeserver.pid
public_baseurl: "http://localhost:8008/"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: false
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse
    password: synapse
    database: synapse
    host: postgres
    cp_min: 5
    cp_max: 10

registration_shared_secret: "change-me"
enable_registration: true

federation_domain_whitelist: []
federation_enabled: false
allow_public_rooms_without_auth: false
allow_public_rooms_over_federation: false

trusted_key_servers: []

suppress_key_server_warning: true

encryption_enabled_by_default_for_room_type: all

presence:
  enabled: true
